### ISSUE TITLE
Distance Calculation

### ISSUE THREAD

**Issue by NoorAlina** [COMP3220-G12/Community-Centre-Locations#1]
Calculating distance between two pairs of latitude and longitude points

**Comment by saffaalvi** [comment]
Found an online formula for calculating distances between two pairs of latitude and longitude points. Referenced in code comments and documentation repository. Made it compatible to work with my code in the Distance class.

**Comment by saffaalvi** [comment]
Found an online formula for calculating distances between two pairs of latitude and longitude points. Referenced in code comments and documentation repository. Made it compatible to work with my code in the Distance class.
